Th2 1819 Added converter JavaType to class in ProtoToIMessageConverter
th2-net/th2-sailfish-utils pull request #20
Opened 2021-05-19 10:45 UTC by Max-81

2021-05-19 12:13 UTC, Nikita-Smirnov-Exactpro requested changes

2021-05-19 12:13 UTC, Nikita-Smirnov-Exactpro commented on build.gradle
> +    implementation 'org.openjdk.jmh:jmh-generator-annprocess:1.28'
!!!Dependencies to JMH shouldn't fall into compile dependency. It should be used only for jmh тест

2021-05-19 14:11 UTC, Nikita-Smirnov-Exactpro submitted a review, later dismissed

2021-05-19 15:04 UTC, jean-michel-perli-sonsin commented on README.md
> ++ Added converter JavaType to class in `ProtoToIMessageConverter` to improve performance
```suggestion
+ Added converter JavaType to the class in `ProtoToIMessageConverter` to improve performance
```

2021-05-19 15:05 UTC, jean-michel-perli-sonsin commented on README.md
>  + Add message properties to the Sailfish IMessage from th2 proto Message
```suggestion
+ Added message properties to the Sailfish IMessage from th2 proto Message
```

2021-05-19 15:12 UTC, jean-michel-perli-sonsin commented on src/main/java/com/exactpro/th2/sailfish/utils/ProtoToIMessageConverter.java
> +        // TODO may be place its logic into the MultiConverter
```suggestion
        // TODO may place its logic into the MultiConverter
```

2021-05-19 15:12 UTC, jean-michel-perli-sonsin commented on src/test/java/com/exactpro/th2/sailfish/utils/SampleBenchmark.java
> + * Copyright 2020-2020 Exactpro (Exactpro Systems Limited)
```suggestion
 * Copyright 2020-2021 Exactpro (Exactpro Systems Limited)
```

2021-05-19 15:13 UTC, jean-michel-perli-sonsin requested changes
Hello, please see if you agree with the small changes proposed below:
- README.md
line 22/26 - **updated** Cradle version. **Introduced** async API for storing events

- src/main/java/com/exactpro/th2/sailfish/utils/ProtoToIMessageConverter.java
line 2 - Copyright 2020-**2021** Exactpro (Exactpro Systems Limited)

Thanks!

2021-05-20 06:57 UTC, Nikita-Smirnov-Exactpro approved these changes

2021-05-20 08:31 UTC, jean-michel-perli-sonsin approved these changes

2021-05-20 08:36 UTC, merged